# Generated by Django 5.2.3 on 2025-06-17 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_path', models.JSONField(blank=True, help_text='Список ID портов в маршруте', null=True)),
                ('result_distance', models.FloatField(blank=True, help_text='Общая дистанция в морских милях', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_tasks_as_end', to='ports.port')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_tasks_as_start', to='ports.port')),
            ],
            options={
                'verbose_name': 'Задача расчета маршрута',
                'verbose_name_plural': 'Задачи расчета маршрутов',
                'ordering': ['-created_at'],
            },
        ),
    ]
