# Generated by Django 5.2.1 on 2025-05-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название порта')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('latitude', models.CharField(max_length=25, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=25, verbose_name='Долгота')),
                ('timezone', models.IntegerField(default=0, verbose_name='Часовой пояс')),
            ],
        ),
    ]
