# Generated by Django 5.2.1 on 2025-05-16 22:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'Порт', 'verbose_name_plural': 'Порты'},
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='port',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='port',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название порта'),
        ),
        migrations.AlterField(
            model_name='port',
            name='timezone',
            field=models.IntegerField(default=0, help_text='UTC+0 = 0, UTC+1 = 1, UTC-1 = -1 и т.д.', validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)], verbose_name='Часовой пояс (Смещение от UTC)'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название маршрута')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('ETA', models.DateTimeField(blank=True, null=True, verbose_name='ETA')),
                ('ETD', models.DateTimeField(blank=True, null=True, verbose_name='ETD')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_waypoints', to='app.port', verbose_name='Порт')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='app.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Маршрутная точка',
                'verbose_name_plural': 'Маршрутные точки',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0, help_text='Расстояние в милях', verbose_name='Расстояние')),
                ('average_speed', models.FloatField(default=0, verbose_name='Средняя скорость')),
                ('estimated_time', models.FloatField(default=0, verbose_name='Расчетное время')),
                ('PortOfArrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_of_arrival', to='app.port', verbose_name='Порт назначения')),
                ('PortOfDeparture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_of_departure', to='app.port', verbose_name='Порт отправления')),
            ],
            options={
                'verbose_name': 'Граф',
                'verbose_name_plural': 'Граф портов',
                'ordering': ['PortOfDeparture', 'PortOfArrival'],
                'unique_together': {('PortOfDeparture', 'PortOfArrival')},
            },
        ),
    ]
