# Generated by Django 5.2.3 on 2025-06-17 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude')),
                ('timezone', models.IntegerField(default=0, help_text='UTC+0 = 0, UTC+1 = 1, UTC-1 = -1 и т.д.', validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)], verbose_name='timezone UTC')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0, help_text='distance in nautical miles', verbose_name='distance')),
                ('average_speed', models.FloatField(blank=True, default=0, verbose_name='average speed')),
                ('estimated_time', models.FloatField(blank=True, default=0, verbose_name='estimated time')),
                ('PortOfArrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_segments', to='ports.port', verbose_name='port of arrival')),
                ('PortOfDeparture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_segments', to='ports.port', verbose_name='port of departure')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'ordering': ['PortOfDeparture__name', 'PortOfArrival__name'],
            },
        ),
    ]
