# Generated by Django 5.2.3 on 2025-06-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cargo, Tanker, High-Speed Craft', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Vessel Type',
                'verbose_name_plural': 'Vessel Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name or identifier for the vessel.', max_length=150)),
                ('average_speed_knots', models.FloatField(help_text='Average operational speed of this specific vessel in knots. Used for ETA calculations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel_type', models.ForeignKey(help_text='The type of the vessel.', on_delete=django.db.models.deletion.PROTECT, to='vessels.vesseltype')),
            ],
            options={
                'verbose_name': 'Vessel',
                'verbose_name_plural': 'Vessels',
                'ordering': ['name'],
            },
        ),
    ]
