# Generated by Django 5.2.3 on 2025-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('ETA', models.DateTimeField(blank=True, null=True, verbose_name='ETA')),
                ('ETD', models.DateTimeField(blank=True, null=True, verbose_name='ETD')),
            ],
            options={
                'verbose_name': 'waypoint',
                'verbose_name_plural': 'waypoints',
                'ordering': ['route', 'order'],
            },
        ),
    ]
