# Generated by Django 5.2.3 on 2025-06-17 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='routewaypoint',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_waypoints', to='ports.port', verbose_name='port'),
        ),
        migrations.AddField(
            model_name='routewaypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route', verbose_name='waypoints'),
        ),
        migrations.AlterUniqueTogether(
            name='routewaypoint',
            unique_together={('route', 'order')},
        ),
    ]
